---
title: "Geo Spatial Analysis of Open Municipal Data"
author: "Gaurav Derasaria, Aniket Shenoy"
date: "2/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(rgdal)
library(leaflet)
library(ggplot2)
library(dplyr)

champaign <- read.csv('data/all_cityworks_records.csv', stringsAsFactors = F)

## data preprocessing

champaign$DESCRIPTION <- as.factor(champaign$DESCRIPTION)
champaign$DATETIMECLOSED <- as.Date(champaign$DATETIMECLOSED, "%m/%d/%Y")
champaign$DATETIMEINIT <- as.Date(champaign$DATETIMEINIT, "%m/%d/%Y")
champaign$STATUS <- as.factor(champaign$STATUS)
champaign$PROBADDRESS <- as.factor(toupper(champaign$PROBADDRESS))


## data cleansing

# removing rows with empty values
champaign <- champaign[!(champaign$SRX=="" | champaign$SRY==""), ]

# removing commas from lat/long
champaign$SRX <- gsub(',',"",champaign$SRX)
champaign$SRY <- gsub(',',"",champaign$SRY)

# subsetting data into OPEN & CLOSED STATUSES
champaign_open = subset(champaign, STATUS=='OPEN' | STATUS=='Open')
champaign_closed = subset(champaign, STATUS=='CLOSED')

champaign_closed$TIMESPAN <- as.numeric(champaign_closed$DATETIMECLOSED - 
  champaign_closed$DATETIMEINIT)

# removing rows where DATETIMECLOSED < DATETIMEINIT
champaign_closed <- champaign_closed[!((champaign_closed$TIMESPAN)<0 | 
                                         is.na(champaign_closed$DATETIMECLOSED)),]

champaign_closed_sorted <- champaign_closed[order(-champaign_closed$TIMESPAN),]


champaign_closed_nad83 <- data.frame(long=as.double(champaign_closed$SRX), 
                                     lat=as.double(champaign_closed$SRY))
champaign_open_nad83 <- data.frame(long=as.double(champaign_open$SRX), 
                                     lat=as.double(champaign_open$SRY))
champaign_closed_sorted_nad83 <- data.frame(long=as.double(champaign_closed_sorted$SRX), 
                                     lat=as.double(champaign_closed_sorted$SRY))

# setting properties of the Spatial df
# EPSG:3435 for given .prj file

coordinates(champaign_closed_nad83) <- c('long','lat')
proj4string(champaign_closed_nad83)=CRS("+init=EPSG:3435")

coordinates(champaign_open_nad83) <- c('long','lat')
proj4string(champaign_open_nad83)=CRS("+init=EPSG:3435")

coordinates(champaign_closed_sorted_nad83) <- c('long','lat')
proj4string(champaign_closed_sorted_nad83)=CRS("+init=EPSG:3435")


#transforming from NAD83 Coordinate Ref. System to WGS84 (standard)
champaign_closed_wgs84 <- spTransform(champaign_closed_nad83, CRS("+init=epsg:4326"))
champaign_open_wgs84 <- spTransform(champaign_open_nad83, CRS("+init=epsg:4326"))
champaign_closed_sorted_wgs84 <- spTransform(champaign_closed_sorted_nad83, 
                                             CRS("+init=epsg:4326"))

icons_closed <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = "green"
)

icons_open <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = "red"
)
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
avg_days_per_issue <- setNames(aggregate(champaign_closed$TIMESPAN, 
                                list(champaign_closed$DESCRIPTION), mean), 
                               c('DESCRIPTION', 'TIMESPAN'))
avg_days_per_issue <- avg_days_per_issue[order(-avg_days_per_issue$TIMESPAN),]

ggplot(avg_days_per_issue[1:10,]) + 
  aes(DESCRIPTION, TIMESPAN) + 
  geom_col(fill='#FF6666') + coord_flip() + 
  xlab(c('Service request')) + ylab(c('Avg days to resolve')) +
  ggtitle('Top 10 requests that took the most time to solve')
```


Requests that have been Closed:

```{r warning=FALSE, message=FALSE, echo=FALSE}
# addProvider used to render maps in html
leaflet(champaign_closed_wgs84) %>% addProviderTiles(providers$OpenStreetMap) %>% 
  addAwesomeMarkers(lng=champaign_closed_wgs84$long, lat=champaign_closed_wgs84$lat, 
                    icon=icons_closed, 
                    label = champaign_closed$DESCRIPTION, 
                    popup = paste("Address:", champaign_closed$PROBADDRESS,
                                  "<br><br>", 
                                  "Problem: ", champaign_closed$DESCRIPTION, 
                                  "<br><br>", 
                                  "Init date: ", champaign_closed$DATETIMEINIT, 
                                  "<br><br>", 
                                  "Days taken to resolve: ", 
                                  champaign_closed$TIMESPAN), 
                    clusterOptions = markerClusterOptions())
```

Requests still open:

```{r warning=FALSE, message=FALSE, echo=FALSE}
leaflet(champaign_open_wgs84) %>% addProviderTiles(providers$OpenStreetMap) %>%
  addAwesomeMarkers(lng=champaign_open_wgs84$long, lat=champaign_open_wgs84$lat, 
                    icon=icons_open, label = champaign_open$DESCRIPTION, 
                    popup = paste("Address:", champaign_open$PROBADDRESS,
                                  "<br><br>", 
                                  "Problem: ", champaign_open$DESCRIPTION, 
                                  "<br><br>", 
                                  "Init date: ", champaign_open$DATETIMEINIT), 
                    clusterOptions = markerClusterOptions())
```

20 requests that took the most time to solve:

```{r warning=FALSE, message=FALSE, echo=FALSE}
# 20 requsts that took the most time to solve  
leaflet(champaign_closed_sorted_wgs84[1:20,]) %>% addProviderTiles(providers$OpenStreetMap) %>% 
  addAwesomeMarkers(lng=champaign_closed_sorted_wgs84$long[1:20], 
                    lat=champaign_closed_sorted_wgs84$lat[1:20], 
                    icon=icons_closed, 
                    label = champaign_closed_sorted$DESCRIPTION[1:20], 
                    popup = paste("Address: ", champaign_closed_sorted$PROBADDRESS[1:20], 
                                  "<br><br>",
                                  "Problem: ", champaign_closed_sorted$DESCRIPTION[1:20],
                                  "<br><br>",
                                  "Init date: ", champaign_closed_sorted$DATETIMEINIT[1:20], 
                                  "<br><br>", 
                                  "Days taken: ", 
                                  champaign_closed_sorted$TIMESPAN[1:20]))

```

<Intensity of circles indicate amount of time taken:>

```{r warning=FALSE, message=FALSE, echo=FALSE}
binpal <- colorBin("Reds", champaign_closed_sorted$TIMESPAN, 4, pretty = FALSE, 
                   reverse = TRUE)
w<-leaflet(champaign_closed_sorted_wgs84[1:20,]) %>% addProviderTiles(providers$OpenStreetMap) %>%
  addCircles(lng = champaign_closed_sorted_wgs84$long[1:20], 
             lat = champaign_closed_sorted_wgs84$lat[1:20], weight = 0.5,
             radius = sqrt(champaign_closed_sorted$TIMESPAN)*20 , 
             color = binpal(champaign_closed_sorted$TIMESPAN),
             popup = paste("Days to solve problem:", 
                           champaign_closed_sorted$TIMESPAN[1:20], sep = ' '))
```

